import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Black Shirt',
      slug: 'black-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 300,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'White Shirt',
      slug: 'white-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 250,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Black Shirt 2',
      slug: 'black-shirt-2',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 200,
      brand: 'Raymond',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'White Shirt 2',
      slug: 'white-shirt-2',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 150,
      brand: 'Oliver',
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Black Shirt 3',
      slug: 'black-shirt-3',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 100,
      brand: 'Zara',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'White Shirt 3',
      slug: 'white-shirt-3',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 50,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
