const data = {
  products: [
    {
      name: 'White Sweatshirt',
      slug: 'white-sweatshirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 200,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'White Sweatshirt2',
      slug: 'white-sweatshirt2',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 150,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'White Sweatshirt3',
      slug: 'white-sweatshirt3',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 100,
      brand: 'Raymond',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'White Sweatshirt4',
      slug: 'white-sweatshirt4',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'White Sweatshirt5',
      slug: 'white-sweatshirt5',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'White Sweatshirt6',
      slug: 'white-sweatshirt6',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 100,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
