import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Emanuel',
      email: 'admin@exemplo.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Beiçola',
      email: 'user@exemplo.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Camisa Preta',
      slug: 'black-shirt',
      category: 'Camisas',
      image: '/images/shirt1.jpg',
      price: 300,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      countInStock: 10,
      description: 'Uma blusa preta popular!',
    },
    {
      name: 'Camisa Branca',
      slug: 'white-shirt',
      category: 'Camisas',
      image: '/images/shirt2.jpg',
      price: 250,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      description: 'Uma camisa branca popular!',
    },
    {
      name: 'Camisa Preta 2',
      slug: 'black-shirt-2',
      category: 'Camisas',
      image: '/images/shirt3.jpg',
      price: 200,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 10,
      countInStock: 10,
      description: 'Uma camisa preta popular!',
    },
    {
      name: 'Camisa Branca 2',
      slug: 'white-shirt-2',
      category: 'Camisas',
      image: '/images/shirt4.jpg',
      price: 150,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      countInStock: 10,
      description: 'Uma camisa branca popular!',
    },
    {
      name: 'Camisa Preta 3',
      slug: 'black-shirt-3',
      category: 'Camisas',
      image: '/images/shirt5.jpg',
      price: 100,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      countInStock: 10,
      description: 'Uma camisa preta popular!',
    },
    {
      name: 'Camisa Branca 3',
      slug: 'white-shirt-3',
      category: 'Camisas',
      image: '/images/shirt6.jpg',
      price: 50,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      description: 'Uma camisa branca popular!',
    },
  ],
};

export default data;
